# mkdocs.yml

site_name: 'Problem Solving 101 with Python'
site_description: 'Website companion for the book Problem Solving 101 with Python by Peter D. Kazarinoff'
site_author: 'Peter D. Kazarinoff'
repo_url: 'https://github.com/ProfessorKazarinoff/Problem-Solving-101-with-Python'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'cyan'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Markdown Extensions
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.arithmatex

# Javascript for MathJax
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

# Extra css
extra_css:
  - 'stylesheets/extra.css'

# Theme Customization
extra:
  social:
    - type: 'globe'
      link: 'https://pcc.edu'
    - type: 'github'
      link: 'https://github.com/professorkazarinoff'
    - type: 'twitter'
      link: 'https://twitter.com/pkazarinoff'

# Copyright
copyright: 'Copyright &copy; 2017 - 2018 Peter D. Kazarinoff'

# Content
pages:
    - Home: index.md
    - Preface:
        - Motivation: 00-Preface/00.00-Motivation.md
        - Acknowledgements: 00-Preface/00.01-Acknowledgements.md
        - Supporting Materials: 00-Preface/00.02-Supporting-Materials.md
        - Formatting Conventions: 00-Preface/00.03-Formatting Conventions.md
        - Errata: 00-Preface/00.04-Errata.md
    - Chapter 1 What is Python?:
        - Introduction: 01-What-is-Python/01.00-Introduction.md
        - What is Python?: 01-What-is-Python/01.01-What-is-Python.md
        - Why Python?: 01-What-is-Python/01.02-Why-Python.md
        - What is Anaconda?: 01-What-is-Python/01.03-What-is-Anaconda.md
        - Summary: 01-What-is-Python/01.04-Summary.md
        - Review Questions: 01-What-is-Python/01.05-Review-Questions.md
    - Chapter 2 Installing Python:
        - Introduction: 02-Installing-Python/02.00-Introduction.md
        - Installing Anaconda on Windows: 02-Installing-Python/02.01-Installing-Anaconda-on-Windows.md
        - Installing Anaconda on MacOS: 02-Installing-Python/02.02-Installing-Anaconda-on-MacOS.md
        - Installing Anaconda on Linux: 02-Installing-Python/02.03-Installing-Anaconda-on-Linux.md
        - Installing Python from Python.org: 02-Installing-Python/02.04-Installing-Python.md
        - Summary: 02-Installing-Python/02.05-Summary.md
    - Chapter 3 Jupyter Notebooks:
        - Introduction: 03-Jupyter-Notebooks/03.00-Introduction.md
        - What is a Jupyter Notebook?: 03-Jupyter-Notebooks/03.01-What-is-a-Jupyter-Notebook.md
        - Why Jupyter Notebooks?: 03-Jupyter-Notebooks/03.02-Why-Jupyter-Notebooks.md
        - Installing Juypter: 03-Jupyter-Notebooks/03.03-Installing-Juypter.md
        - Opening a Jupyter Notebook: 03-Jupyter-Notebooks/03.04-Opening-a-Jupyter-Notebook.md
        - The Jupyter Notebook Interface: 03-Jupyter-Notebooks/03.05-The-Jupyter-Notebook-Interface.md
        - Magic Cells: 03-Jupyter-Notebooks/03.06-Magic-Cells.md
        - Getting Help in a Jupyter Notebook: 03-Jupyter-Notebooks/03.07-Getting-Help-in-a-Jupyter-Notebook.md
        - Summary: 03-Jupyter-Notebooks/03.08-Summary.md
        - Review Questions: 03-Jupyter-Notebooks/03.09-Review-Questions.md
    - Chapter 4 The Python REPL:
        - Introduction: 04-The-Python-REPL/04.00-Introduction.md
        - Python as a fancy calculator: 04-The-Python-REPL/04.01-Python-as-a-fancy-calculator.md
        - Variables: 04-The-Python-REPL/04.02-Variables.md
        - Data Types: 04-The-Python-REPL/04.03-Data-Types.md
        - Boolean Arithmetic: 04-The-Python-REPL/04.04-Boolean-Arithemtic.md
        - Print Statements: 04-The-Python-REPL/04.05-Print-Statements.md
        - String Operations: 04-The-Python-REPL/04.06-String-Operations.md
        - Summary: 04-The-Python-REPL/04.07-Summary.md
        - Review Questions: 04-The-Python-REPL/04.08-Review-Questions.md
    - Chapter 5 Plotting with Matplotlib:
        - Introduction: 05-Plotting-with-Matplotlib/05.00-Introduction.md
        - What is Matplotlib?: 05-Plotting-with-Matplotlib/05.01-What-is-Matplotlib.md
        - Installing Matplotlib: 05-Plotting-with-Matplotlib/05.02-Installing Matplotlib.md
        - Customizing matplotlib plots: 05-Plotting-with-Matplotlib/05.03-Line-Plots.md
        - Saving plots: 05-Plotting-with-Matplotlib/05.04-Saving-Plots.md
        - Multi Line Plots: 05-Plotting-with-Matplotlib/05.05-Multi-Line-Plots.md
        - Bar Charts: 05-Plotting-with-Matplotlib/05.06-Bar-Charts.md
        - Pie Charts: 05-Plotting-with-Matplotlib/05.07-Pie-Charts.md
        - Histograms: 05-Plotting-with-Matplotlib/05.08-Histograms.md
        - Scatter Plots: 05-Plotting-with-Matplotlib/05.09-Scatter-Plots.md
        - Summary: 05-Plotting-with-Matplotlib/05.10-Summary.md
        - Review Questions: 05-Plotting-with-Matplotlib/05.11-Review-Questions.md
    - Chapter 6 User Input and Loops:
        - Introduction: 06-User-Input-and-Loops/06.00-Introduction.md
        - f-Strings: 06-User-Input-and-Loops/06.01-f-Strings.md
        - User Input: 06-User-Input-and-Loops/06.02-User-Input.md
        - For Loops: 06-User-Input-and-Loops/06.03-For-Loops.md
        - While Loops: 06-User-Input-and-Loops/06.04-While-Loops.md
        - If statements: 06-User-Input-and-Loops/06.05-If-Statements.md
        - Summary: 06-User-Input-and-Loops/06.06-Summary.md
        - Review Questions: 06-User-Input-and-Loops/06.07-Review-Questions.md
    - Appendix:
        - Contents: 99-Appendix/99.00-Appendix.md
        - Reserved and Key Words in Python: 99-Appendix/99.01-Reserved-and-Key-Words-in-Python.md
        - Python Built-in Functions: 99-Appendix/99.02-Built-in-Functions.md
        - Math and Statistics Module Functions: 99-Appendix/99.03-Math-and-Statistics-Module-Functions.md
        - NumPy Math Functions: 99-Appendix/99.04-Numpy-Math-Functions.md
        - Virtual Environments: 99-Appendix/99.05-Virtual-Environments.md
        - Problem Solving 101 with Python Book Construction: 99-Appendix/99.06-Problem-Solving-101-with-Python-Book-Construction.md
        - Problem Solving 101 with Python Book Construction: 99-Appendix/99.07-Problem-Solving-101-with-Python-Book-Construction.md
        - Contributions: 99-Appendix/99.08-Contributions.md
        - About the Author: 99-Appendix/99.09-About-the-Author.md